export enum FileUploadConstant {
  FILE_UPLOAD_REQUEST = "FILE_UPLOAD_REQUEST",
  FILE_UPLOAD_SUCCESS = "FILE_UPLOAD__SUCCESS",
  FILE_UPLOAD_ERROR = "FILE_UPLOAD__ERROR",
  FETCH_FILES_REQUEST = "FETCH_FILES_REQUEST",
  FETCH_FILES_SUCCEED = "FETCH_FILES_SUCCEED",
  RESET_STORE = "RESET_STORE",
}
